books/books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("pens.urls")),
    path("admin/", admin.site.urls),
]

books/pens/urls.py
from django.urls import path
from . import views

app_name = "pens"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("add", views.create, name="add"),
    path("<id>/edit", views.edit, name="edit"),
    path("<id>/delete", views.delete, name="delete"),
    path("<id>/", views.show, name="show"),
]

books/pens/models.py
from django.db import models


class Pen(models.Model):
    number = models.CharField(max_length=100)
    length = models.CharField(max_length=50)
    description = models.TextField(max_length=200)

books/pens/forms.py
from django import forms
from .models import Pen


# class = ModelForm(Form) 繼承表單
class PenForm(forms.ModelForm):
    # forms 裡面的 ModelForm 方法，剛剛是一般表單操作，現在是跟 model 有關的表單操作
    class Meta:  # class 裡面的 class
        model = Pen  # 指定 model

        fields = ["number", "length", "description"]  # 1
        # 有哪些欄位
        # 2. 如果欄位太多可用 exclude=[" "]
        # 3. fields = "__all__" 故意暴露所有
        labels = {
            # 用 label 字典更新欄位
            "number": "姓名",
            "length": "長度",
            "description": "描述",
        }


# class PenForm(forms.Form):
#     number = forms.CharField(label="number", max_length=100)
#     length = forms.CharField(label="length", max_length=50)
#     description = forms.CharField(label="description", widget=forms.Textarea)

books/pens/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Pen
from .forms import PenForm
from django.contrib import messages


# Create your views here.

def index(req):
    pens = Pen.objects.all()
    return render(req, "pens/index.html", {"pens": pens})


def show(req, id):
    pen = get_object_or_404(Pen, pk=id)
    if req.method == "POST":
        # form = PenForm(req.POST)  # 我要新增的東西
        # form = PenForm(instance=pen)  # 目前有的東西
        form = PenForm(req.POST, instance=pen)
        if form.is_valid():
            form.save()
        # return redirect(f"/{pen.id}")
        return redirect("pens:show", id=pen.id)
    else:
        return render(req, "pens/show.html", {"pen": pen})


def new(req):
    form = PenForm()  # 建立表單物件
    return render(req, "pens/new.html", {"form": form})


@require_POST
def create(req):
    form = PenForm(req.POST)  # 建立表單，把整坨東西餵給他
    if form.is_valid():  # 是否是有效的（某個欄位是必填），在model之前就先做篩選
        form.save()  # 驗證過就叫表單存檔

        messages.success(req, "新增成功！")  # 新增成功的訊息，只會出現一次（規則）

    return redirect("pens:index")


def edit(req, id):
    pen = get_object_or_404(Pen, pk=id)
    form = PenForm(instance=pen)
    return render(req, "pens/edit.html", {"pen": pen, "form": form})
    # 注意！render 函數只接受一個字典函數


@require_POST
def delete(req, id):
    pen = get_object_or_404(Pen, pk=id)
    pen.delete()
    messages.error(req, "資料已刪除！")
    return redirect("pens:index")

books/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pen</title>
</head>
<body>
    {% include "shared/message.html" %}

    {% block content %}{% endblock %}
</body>
</html>

books/templates/pens/edit.html
{% extends 'layouts/base.html' %}
{% block content %}
<h1>編輯頁面</h1>
<form action="{% url 'pens:show' pen.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit"value="編輯">
</form>
{% endblock %}

books/templates/pens/index.html
{% extends 'layouts/base.html' %}
{% block content %}
{% comment %}  
# form 不寫 get or post 代表預設 get(我這頁)
{% endcomment %}
<form>   
    <input type="search" name="keyword">
    <button>搜尋</button>
</form>
<h1>首頁</h1>
<a href="{% url 'pens:new' %}">新增</a>

{% for pen in pens %}
    <a href="{% url 'pens:show' pen.id %}">{{ pen.number }}</a>
{% endfor %}
{% endblock %}

books/templates/pens/new.html
{% extends 'layouts/base.html' %}
{% block content %}
<h1>新增pens</h1>
<form action="{% url 'pens:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    
    <input type="submit"value="新增">
</form>
{% endblock %}

books/templates/pens/show.html
{% extends 'layouts/base.html' %}
{% block content %}
<h1>Pen List</h1>
<h1>{{ pen.number }}</h1>
<h1>{{ pen.length }}</h1>
<h1>{{ pen.description }}</h1>
<a href="{% url 'pens:edit' pen.id %}">編輯</a>
<form action="{% url 'pens:delete' pen.id %}" method="post">
    {% csrf_token %}
    <button>delete</button>
</form>
{% endblock %}

books/templates/shared/message.html
{% if messages %} 
        {% for message in messages %} 
            {{ message }}
        {% endfor %}
{% endif %}