posts/urls.py
from django.urls import path
from . import views

app_name = "postes"
urlpatterns = [
    path("", views.home, name="index"),
    path("new", views.new, name="new"),
    path("add", views.create, name="add"),
    path("<id>/edit", views.edit, name="edit"),
    path("<id>/delete", views.delete, name="delete"),
    path("<id>", views.show, name="show"),
]

posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    number = models.CharField(max_length=5)
    note = models.TextField(default="")

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Post


def home(request):
    posts = Post.objects.all()
    return render(request, "posts/index.html", {"posts": posts})


def new(request):
    return render(request, "posts/new.html")


@require_POST
def create(request):
    post = Post(
        title=request.POST["title"],
        number=request.POST["number"],
        note=request.POST["note"],
    )
    post.save()
    return redirect("postes:index")


def show(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        post.title = request.POST["title"]
        post.number = request.POST["number"]
        post.note = request.POST["note"]
        post.save()
        return redirect(f"/{post.id}")
    else:
        return render(request, "posts/show.html", {"post": post})


def edit(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, "posts/edit.html", {"post": post})


@require_POST
def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect("postes:index")

posts/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

posts/templates/posts/edit.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1>Edit</h1>
    <form action="{% url 'postes:show' post.id %}" method="post">
        {% csrf_token %}
        <div>
            <label for="title">title</label>
            <input type="text" name="title" id="title" value="{{ post.title }}">
        </div>
        <div>
            <label for="number">number</label>
            <input type="text" name="number" id="number" value="{{ post.number }}">
        </div>
        <div>
            <label for="note">title</label>
            <input type="text" name="note" id="note" value="{{ post.note }}">
        </div>
        <input type="submit" value="編輯">
    </form>
{% endblock %}

posts/templates/posts/index.html
{% extends 'layouts/base.html' %}

{% block content %}
<h1>部落格首頁</h1>
<a href="{% url 'postes:new' %}">新增</a>
{% for post in posts %}
<div>
    <a href="{% url 'postes:show' post.id %}">{{ post.title }}</a>
</div>
{% endfor %}
{% endblock %}

posts/templates/posts/new.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1>New</h1>
    <form action="{% url 'postes:add' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="title">title</label>
            <input type="text" name="title" id="title">
        </div>
        <div>
            <label for="number">number</label>
            <input type="text" name="number" id="number">
        </div>
        <div>
            <label for="note">title</label>
            <input type="text" name="note" id="note">
        </div>
        <input type="submit" value="新增">
    </form>
{% endblock %}

posts/templates/posts/show.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1>貼文列表</h1>
    <p>{{ post.title }}</p>
    <p>{{ post.number }}</p>
    <p>{{ post.note }}</p>

    <a href="{% url 'postes:edit' post.id %}">Edit</a>
    <form action="{% url 'postes:delete' post.id %}" method="post">
        {% csrf_token %}
        <button>Delete</button>
    </form>
{% endblock %}